// FAKE DATA
export const books = [
    {
      id: 1,
      title: "Attack On Titan Vol. 25",
      url: "https://m.media-amazon.com/images/I/51eTlt4L2pL.jpg",
      originalPrice: 49.95,
      salePrice: 14.95,
      rating: 4.5,
    },
    {
      id: 2,
      title: "Attack On Titan Vol. 28",
      url: "https://m.media-amazon.com/images/I/51-hVK+CCJL.jpg",
      originalPrice: 39,
      salePrice: null,
      rating: 5,
    },
    {
      id: 3,
      title: "Mieruko-chan Vol. 1",
      url: "https://m.media-amazon.com/images/I/51ypMZ+HabL.jpg",
      originalPrice: 29,
      salePrice: null,
      rating: 5,
    },
    {
      id: 4,
      title: "Chainsaw man Vol. 2",
      url: "https://m.media-amazon.com/images/I/71V4HkDbmtL._AC_UF1000,1000_QL80_.jpg",
      originalPrice: 44,
      salePrice: 19,
      rating: 4.5,
    },
    {
      id: 5,
      title: "Death Note Vol. 1 Black Edition",
      url: "https://prodimage.images-bn.com/pimages/9781421539645_p0_v2_s1200x630.jpg",
      originalPrice: 32,
      salePrice: null,
      rating: 5,
    },
    {
      id: 6,
      title: "Goodnight Punpun Vol. 1",
      url: "https://m.media-amazon.com/images/I/61P35IvoVFL.jpg",
      originalPrice: 70,
      salePrice: 12.5,
      rating: 5,
    },
    {
      id: 7,
      title: "Jujutsu Kaisen Vol. 1",
      url: "https://m.media-amazon.com/images/I/51zXJBloNpL._AC_UF1000,1000_QL80_.jpg",
      originalPrice: 11,
      salePrice: 10,
      rating: 4,
    },
    {
      id: 8,
      title: "Jujutsu Kaisen Vol. 2",
      url: "https://m.media-amazon.com/images/I/815taz8gMaL._AC_UF1000,1000_QL80_.jpg",
      originalPrice: 38,
      salePrice: 17.95,
      rating: 4.5,
    },
    {
      id: 9,
      title: "Jujutsu Kaisen Vol. 4",
      url: "https://m.media-amazon.com/images/I/814Ppc2uVOL._AC_UF1000,1000_QL80_.jpg",
      originalPrice: 35,
      salePrice: 19.95,
      rating: 4.5,
    },
    {
      id: 10,
      title: "Mob Psycho 100 Vol. 1",
      url: "https://m.media-amazon.com/images/I/A1AUygBZJtL._AC_UF1000,1000_QL80_.jpg",
      originalPrice: 40,
      salePrice: null,
      rating: 5,
    },
    {
      id: 11,
      title: "One piece Vol. 96",
      url: "https://images.booksense.com/images/990/719/9781974719990.jpg",
      originalPrice: 30,
      salePrice: 20,
      rating: 5,
    },
    {
      id: 12,
      title: "My Home Hero Vol. 1",
      url: "https://m.media-amazon.com/images/I/41vpNabkDTL.jpg",
      originalPrice: 30,
      salePrice: 12.95,
      rating: 4.5,
    },
  ];